### ISSUE TITLE
brew desc showing some formulas do not have description

### ISSUE THREAD

**Issue by hanxue** [telemachus/homebrew-desc#59]
When I run this command

```
$ brew desc -s a|grep "description yet"
partio: No description yet
pax-construct: No description yet
pax-runner: No description yet
pixman: No description yet
qtfaststart: No description yet
rsstail: No description yet
rtpbreak: No description yet
runcocoa: No description yet
s-lang: No description yet
saga-core: No description yet
```

I got a list of formulas that `brew-desc` claims do not have a description yet. But this is not true:

```
$ grep partio /usr/local/Library/Taps/telemachus/homebrew-desc/cmd/brew-desc.rb 
  "partio" => "Particle library for 3D graphics",
```

I have tried untapping and re-tapping `telemachus/desc` but I still get the same list of formulas without description. How can I get those missing description?

**Comment by telemachus** [comment]
That is very odd, I agree. I can't reproduce it here, however.

Can you try this, please?

     brew uninstall -f brew-desc && brew untap telemachus/desc && brew cleanup

Then run `ls` to make sure that every trace of `brew-desc` is gone. After that, re-tap and reinstall and see if the problem goes away.

**Comment by hanxue** [comment]
Hello @telemachus , I have followed your instructions and now I no longer find any Formulas without descriptions:

```
$ brew desc -s a|grep "description yet"
```

Perhaps because there is an older version of `brew-desc` installed somewhere. 

Thanks for your help!
