### ISSUE TITLE
Extend brew-desc to 'homebrew-science' and others.

### ISSUE THREAD

**Issue by hansgru** [telemachus/homebrew-desc#63]
Please extend brew-desc to use 'homebrew-science' and others too.

**Comment by telemachus** [comment]
I have to admit that I don't have any plans to do this at present. It's a lot just keeping up with `homebrew/master`, and I also don't have even the other major taps installed here. But I'll consider it for sometime in the future.

Thanks.

**Comment by bfontaine** [comment]
@telemachus Would you consider a system to extend `brew-desc` from a tap? I don’t have something specific in mind, but for example a Ruby file called `descriptions.rb` at the root of a tap directory, then `brew-desc` just have to do something like:

```rb
Dir["#{HOMEBREW_PREFIX}/Library/Taps/*/*/descriptions.rb"].each do |d|
  require d
end
```

and each `description.rb` file uses a way to extend the `descriptions` hash. You could also use a slower solution which is to put the descriptions in a text file (this is what I’m doing with [homebrew-command-not-found](https://github.com/bfontaine/homebrew-command-not-found/blob/master/executables.txt)) then if you don’t find a formula fallback on the taps.

Also, `brew-desc` would then have to deal with name conflicts. The easy way is to require the user to use the absolute name of the formula, e.g. `git` (main repo) vs `homebrew/x11/morse` (tap).

**Comment by telemachus** [comment]
> Would you consider a system to extend brew-desc from a tap?

Yes, I would. I also don't know the best way to do this, but I would consider it.

> Also, `brew-desc` would then have to deal with name conflicts.

My instinct here is to have `brew desc` handle conflicts just like `brew` itself does. For example, if I have a tap with a `vim` formula (and I do), here's how `brew` deals with it.

+ If I write `brew install vim`, `brew` installs its own, default `vim`.
+ If I want to install *my* `vim`, then as you say, I must specify `brew install telemachus/brew/vim`.

I think that's the sanest thing to do, but I'm open to other suggestions from people.

**Comment by bfontaine** [comment]
> I think that's the sanest thing to do

Agreed.

**Comment by telemachus** [comment]
Closed because the repo is no longer active.
