### ISSUE TITLE
NoMethodError upgrading 

### ISSUE THREAD

**Issue by drevicko** [telemachus/homebrew-desc#89]
during a `brew upgrade`, brew-desc threw this error:

```
==> Upgrading 1 outdated package:
telemachus/desc/brew-desc 0.9.151 -> 0.9.156
==> Upgrading telemachus/desc/brew-desc 
==> Cloning https://github.com/telemachus/homebrew-desc.git
Updating /Users/drevicko/Library/Caches/Homebrew/brew-desc--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 2d28623 Updated as of 2015-10-05
Error: An exception occurred within a child process:
  NoMethodError: undefined method `undent' for #<String:0x00007f9644105a18>
```

Seems the 'undent' method has been deprecated (eg: see [here](https://github.com/Homebrew/homebrew-cask/issues/49716)).

One question: since brew-desc is now in brew, can I safely remove it?

**Comment by telemachus** [comment]
> One question: since brew-desc is now in brew, can I safely remove it?

Yes. It should be as easy as untapping brew-desc and upgrading again.

Please reopen or comment if you have any trouble after that.
